Adds fancy UI
TheGreyDiamond/UnitFilter pull request #3
Opened 2021-10-07 06:35 UTC by TheGreyDiamond

Don't merge yet, but this will add a cool ui.

- [x] Finish landing page

2021-10-07 19:06 UTC, TheGreyDiamond commented
The landing page is done, @XilefTech  please look through his to check if you agree!

2021-10-08 06:54 UTC, XilefTech reviewed
seems fine so far... just look at the few points I annotated again pls

2021-10-08 06:54 UTC, XilefTech commented on .vscode/settings.json
> +{
don't ya think this should go into the gitignore? everyone has their own python paths and stuff...

2021-10-08 06:54 UTC, XilefTech commented on templates/index.html
> +           This happens because many schools don't setup their WebUntis Instance very good. But <b>UnitFilter</b> is here to help.
I'd say "very well" instead of good

2021-10-08 14:07 UTC, XilefTech requested changes
found some more things

2021-10-08 14:07 UTC, XilefTech commented on templates/register.html
> +      <input class="shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker" id="email" type="text" placeholder="john.doe@example.com" name="email" value="{{ request.form.email }}">
you can make this type email again

2021-10-08 14:07 UTC, XilefTech commented on templates/register.html
> +      <input class="shadow appearance-none border border-red rounded w-full py-2 px-3 text-grey-darker mb-3" id="class_password" name="class_password" type="text" placeholder="Your Class password" va
shouldn't this be type password as well?

2021-10-08 18:16 UTC, XilefTech commented on templates/index.html
> +          We help you filter and sort your WebUntis to make it more sane. Displying only the courses you <b>really</b> care about.
typo in displaying ;)

also you can make these paragraphs a bit bigger in text size

2021-10-08 19:30 UTC, XilefTech approved these changes

2021-10-08 19:30 UTC, merged